name: 'Conflicting CA & Logger'
 
on:
  workflow_dispatch:
  
concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true
 
jobs:
  run-network-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'

      - name: Run Network Test 2 
        run: |
          cd tests/networktests/Test2
          go run Test2.go CA 1 &
          go run Test2.go Logger 1 &
          go run Test2.go Monitor 1 &
          go run Test2.go Monitor 2 &
          go run Test2.go Monitor 3 &
          go run Test2.go Monitor 4 &
          go run Test2.go Gossiper 1 &
          go run Test2.go Gossiper 2 &
          go run Test2.go Gossiper 3 &
          go run Test2.go Gossiper 4 &
          sleep 200
          go test 
